version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
    - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
    - IMAGE_URI=${REPOSITORY_URI}:${TAG}
  build:
    commands:
    - echo Build started on `date`
    - mvn clean package
  post_build:
    commands:
    - printenv
    - echo Build completed on `date`
artifacts:
  files:
  - imagedefinitions.json
